import jsPDF from "jspdf";

export const generatePDFReport = (result) => {
  const pdf = new jsPDF();
  
  const reportTitle = `ClauseWise Analysis Report - ${result.documentName}`;
  const timestamp = new Date().toLocaleString();

  let content = `${reportTitle}\n`;
  content += `Generated on: ${timestamp}\n`;
  content += `====================================================\n\n`;

  content += `SUMMARY\n`;
  content += `----------------------------------------------------\n`;
  content += `Contract Type: ${result.contractType || 'N/A'}\n`;
  content += `Safety Score: ${result.safetyScore}/100\n`;
  content += `Verdict: ${result.verdict}\n`;
  content += `Summary: ${result.summary}\n\n`;

  content += `STATS\n`;
  content += `----------------------------------------------------\n`;
  content += `- Safe Clauses: ${result.stats.safe}\n`;
  content += `- Caution Clauses: ${result.stats.caution}\n`;
  content += `- Unsafe Clauses: ${result.stats.unsafe}\n\n`;

  content += `CLAUSE-BY-CLAUSE ANALYSIS\n`;
  content += `----------------------------------------------------\n`;

  result.clauses.forEach((clause, index) => {
    content += `[${index + 1}] § ${clause.number}: ${clause.title}\n`;
    content += `Risk Level: ${clause.risk.toUpperCase()}\n`;
    content += `Plain English:\n${clause.plainEnglish}\n`;

    if (clause.legalNote) {
      content += `Legal Note: ${clause.legalNote}\n`;
    }

    content += `Snippet:\n${clause.originalText.substring(0, 300)}${clause.originalText.length > 300 ? '...' : ''}\n`;
    content += `----------------------------------------------------\n`;
  });

  content += `\nDisclaimer: This report was generated by AI for informational purposes only and does not constitute legal advice.`;

  // Split long text into pages
  const lines = pdf.splitTextToSize(content, 180);

  let y = 10;
  const lineHeight = 7;

  lines.forEach((line) => {
    if (y > 280) {
      pdf.addPage();
      y = 10;
    }
    pdf.text(line, 10, y);
    y += lineHeight;
  });

  pdf.save(`ClauseWise_Report_${result.documentName.replace(/\.[^/.]+$/, "")}.pdf`);
};
